# This workflow will publish a package when a release is created

name: Publish package to NuGet repository
on:
  release:
    types: [created]

jobs:
  publish-npm:  
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
      - name: Build solution and generate NuGet package
        run: |
          cd contentstack-dotnet
          dotnet pack -c Release -o out

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./contentstack-dotnet/out/*.nupkg --api-key ${{NUGET_AUTH_TOKEN}} --skip-duplicate --no-symbols true

  publish-git:  
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/Contentstack/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build solution and generate NuGet package
        run: |
          cd contentstack-dotnet
          dotnet pack -c Release -o out

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./contentstack-dotnet/out/*.nupkg --api-key ${{NUGET_AUTH_TOKEN}} --skip-duplicate --no-symbols true
