name: Unit Test
on:
  pull_request:
  push:

jobs:
  unit-test:  
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4.3.0
      - name: Run unit tests
        run: dotnet test Contentstack.Core.Unit.Tests/Contentstack.Core.Unit.Tests.csproj --verbosity normal

